export default {
  auth: {
    login: 'Sign In',
    register: 'Sign Up',
  },
  nav: {
    home: 'Home',
  },
  followUs: 'Follow eXitus On',
  footer: {
    menu: {
      hub: {
        title: 'Hub',
      },
      store: {
        title: 'Store',
      },
      more: {
        title: 'More',
      },
      social: {
        title: 'Social',
      },
      help: {
        title: 'Help',
        contact: 'Contact',
      },
    },
    copyright: 'All rights reserved.',
    created: 'Created with {heart} in Germany',
    privacy: 'Privacy Policy',
    terms: 'Terms & Conditions',
    imprint: 'Imprint',
  },
  pre: {
    headline: 'We are getting ready',
    sub: 'Subscribe to know more about the first release of eXitus.',
    signUpEA: 'Sign up for early access',
    followUs: 'Follow us',
    features: {
      ghosts: {
        title: 'Ghosts',
        text: 'You have collected Ghosts through our service? You can exchange them for hardware, games or in-game items soon! So don\'t stop making challenges, it will be worth it!',
      },
      challenges: {
        title: 'Challenges',
        text: 'Get Ghosts through our new Challenge System. Get new challenges, missions or co-op challenges every day. Or at events with a time limit.',
      },
      store: {
        title: 'Store',
        text: 'Buy premium, games, hardware and in-game items through our store. Pay with Our Ghosts or support our community and pay with one of our many payment providers.',
      },
      hubs: {
        title: 'Hubs',
        text: 'Our hub system offers you many opportunities to work with our community. There is an area for maps, textures, ideas or questions and much more.',
      },
    },
  },
  countdown: {
    days: 'Days',
    day: 'Day',
    hours: 'Hours',
    hour: 'Hour',
    minutes: 'Minutes',
    minute: 'Minute',
    seconds: 'Seconds',
    second: 'Second',
  },
  country: {
    germany: 'Germany',
  },
  imprint: {
    title: 'Legal notice',
    updated: 'Last updated:',
    description: 'Here you can find out who is responsible for these websites. If you need help, please contact customer service.',
    general: {
      company: 'Company name',
      address: 'Address',
      phone: 'Phone',
      contact: 'Contact',
      ceo: 'CEO',
      registry: 'Company Registry',
      vat: 'VAT No.',
      important: {
        title: 'Important note',
        description: 'All prices listed on the homepage are inclusive of the statutory VAT (currently 19%).',
      },
      legal: {
        title: 'Legal notice',
        description: 'All texts and graphics published on {url} are subject to copyright and may not be used without the consent of the author. Reproduction or dissemination of individual contents or complete pages without prior consent will be prosecuted both under criminal and civil law. vega UG(haftungsbeschränkt) is not responsible for the content of the pages, which is indicated by a link (URL), but the respective information provider. vega UG(haftungsbeschränkt) does not guarantee the accessibility and timeliness of the linked URLs. We assume no liability for damages resulting from the use of this site. Place of fulfillment and exclusive court of jurisdiction is Hamburg.',
      },
      onlineDispute: {
        title: 'Online dispute resolution pursuant to Article 14 (1) ODR-VO',
        description: 'The European Commission is providing an online dispute resolution platform, which can be found at {url}.',
      },
      paymentDe: {
        title: 'Payment for customers from Germany',
        data: {
          recipient: 'Recipient:',
          bank: 'Bank:',
          address: 'Address:',
          city: 'City:',
          iban: 'IBAN:',
          swift: 'BIC:',
        },
      },
      paymentInt: {
        title: 'Internationales Payment',
        data: {
          recipient: 'Recipient:',
          bank: 'Bank:',
          address: 'Address:',
          city: 'City:',
          iban: 'IBAN:',
          swift: 'SWIFT/BIC:',
        },
      },
    },
  },
  terms: {
    title: 'Terms & Conditions',
    updated: 'Last updated:',
  },
  privacy: {
    title: 'Privacy policy',
    updated: 'Last updated:',
    description: 'We are pleased about your visit to our website and your interest in our offers. The protection of your personal data is an important concern to us, so that we want to inform you here in detail about the handling of your personal data. Personal data is all data that can be related to you personally, e.g. your name, address, e-mail addresses, user behaviour.',
    general: {
      headline: 'General:',
      secondHeadline: 'Name and address of the person responsible',
      description: 'The person responsible within the meaning of the General Data Protection Regulation („GDPR“) and other national data protection laws of the member states as well as other data protection provisions is the Data Protection Supervisor:',
      data: {
        headline: 'Name and address of data protection officer',
        description: 'The data protection officer of the person responsible is:',
      },
    },
    data: {
      processing: {
        headline: 'General information on data processing:',
        description: 'Scope of the processing of personal data / encryption:',
        h: {
          1: 'Legal basis for the processing of personal data:',
          2: 'Data deletion and storage duration:',
          3: 'Revocation:',
          4: 'Data processing for individual usage types',
          5: 'Collection of personal data when you visit our website',
          6: 'Description and scope of data processing',
          7: 'Legal basis for data processing',
          8: 'Purpose of data processing',
          9: 'Duration of storage',
          10: 'Possibility of opposition and removal',
        },
        p: {
          1: 'The use of our website functions is basically possible without the processing of personal data. For the (personal) data that you have technically transmitted to us, please refer to the corresponding remarks below.',
          2: 'We process the personal data of our users only to the extent necessary to provide a functioning website. The processing of personal data of our users is carried out regularly only with the consent of the user. An exception applies in those cases where prior consent cannot be obtained for actual reasons and the processing of the data is permitted by statutory provisions, e.g. to fulfil our contractual obligations.',
          3: 'Our website uses SSL or TLS encryption for security reasons and to protect the transmission of personal data and other confidential content (e.g. orders). You can recognize an encrypted connection by the character string „https://“ and the lock symbol in your browser line.',
          4: 'In accordance with Article 13 of the General Data Protection Regulation (GDPR), we inform you of the legal basis of our data processing. If the legal basis is not mentioned in the data protection declaration, the following applies:',
          5: 'If we obtain the consent of the data subject for the processing of personal data, Art. 6 para. 1 lit. a EU GDPR serves as the legal basis.',
          6: 'Art. 6 para. 1 lit. b GDPR serves as a legal basis for the processing of personal data required for the performance of a contract to which the data subject is a party. This also applies to processing operations that are necessary to carry out pre-contractual measures.',
          7: 'As far as a processing of personal data is necessary for the fulfilment of a legal obligation (e.g. fulfilment of fiscal archiving obligations) to which our company is subject, Art.6 para. 1 lit. c GDPR serves as legal basis.',
          8: 'In the event that vital interests of the data subject or another natural person necessitate the processing of personal data, Art. 6 para. 1 lit. d GDPR serves as the legal basis.',
          9: 'If the processing is necessary to safeguard a legitimate interest of our company or a third party and if the interests, fundamental rights and fundamental freedoms of the data subject do not outweigh the first-mentioned interest, Art. 6 para. 1 lit. f GDPR serves as the legal basis for the processing.',
          10: 'The personal data of the data subject will be deleted or blocked as soon as the purpose of the storage no longer applies. In addition, the data may be stored if the European or national legislator has provided for this in EU ordinances, laws or other regulations to which the person responsible is subject. The data shall also be blocked or deleted if a storage period prescribed by the aforementioned standards expires, unless it is necessary for further storage of the data for the conclusion or performance of a contract.',
          11: 'If you have given one or more consent(s) for data processing, you can freely revoke this consent(s) at any time for the future. For the revocation you can use the contact data of the responsible person mentioned above. The revocation does not incur any costs for you and has no negative consequences for you. The lawfulness of the processing of your data before your revocation remains unaffected in this case. Please also note the rights of data subjects described in detail below.',
          12: 'Each time you access our website, our system automatically collects data and information from the computer system of the accessing computer. The following data is collected:',
          13: 'The data is also stored in the log files of our system. These data are not stored together with other personal data of the user.',
          14: 'The legal basis for the temporary storage of data and log files is Art. 6 para. 1 lit. f GDPR.',
          15: 'The temporary storage of the IP address by the system is necessary to enable delivery of the website to the user\'s computer. For this purpose, the IP address of the user must remain stored for the duration of the session.',
          16: 'The data is stored in log files to ensure the functionality of the website. The data is also used to optimise the website and to ensure the security of our information technology systems. An evaluation of the data for marketing purposes does not take place in this context.',
          17: 'These purposes also include our legitimate interest in data processing pursuant to Art. 6 para. 1 lit. f GDPR.',
          18: 'The data are deleted as soon as they are no longer required for the purpose of their collection. In the case of the collection of data to provide the website, this is the case when the session in question has ended.',
          19: 'If the data is stored in log files, this is the case after 30 days at the latest. A storage going beyond this is possible. In this case, the IP addresses of the users are deleted or alienated, so that an assignment of the calling client is no longer possible.',
          20: 'The collection of data for the provision of the website and the storage of data in log files is mandatory for the operation of the website. Consequently, there is no possibility for the user to object.',
        },
        ul: {
          1: 'Information about the browser type and the version used',
          2: 'The user\'s operating system',
          3: 'The Internet service provider of the user',
          4: 'The IP address of the user',
          5: 'Date and time of access',
          6: 'Websites from which the user\'s system accesses our website',
          7: 'Websites accessed by the user\'s system through our website',
          8: 'Access status/HTTP status code',
          9: 'The amount of data transferred',
        },
        cookies: {
          headline: 'Use of cookies',
          h: {
            1: 'Description and scope of data processing',
            2: 'Legal basis for data processing',
            3: 'Purpose of data processing',
            4: 'Duration of storage, possibility of objection and removal',
          },
          p: {
            1: 'Our website uses so-called „cookies“. Cookies are small text files that are transferred from a website server to your hard drive and stored. This automatically provides us with certain data such as IP address, language and browser used, operating system, etc. When a user visits a website, a cookie can be stored on the user\'s operating system. This cookie contains a characteristic string of characters that enables the browser to be uniquely identified when the website is called up again.',
            2: 'Technically necessary cookies',
            3: 'We use cookies to make our website more user-friendly. Some elements of our website require that the calling browser can be identified even after a page change.',
            4: 'The following data is stored and transmitted in the cookies:',
            5: 'Cookies that are not technically necessary',
            6: 'We also use cookies on our website which enable us to analyse the surfing behaviour of our users. In this way, the following data can be transmitted:',
            7: 'The user data collected in this way is pseudonymised by technical precautions. It is therefore no longer possible to assign the data to the calling user. The data are not stored together with other personal data of the user.',
            8: 'When calling up our website, the user is informed about the use of cookies for analysis purposes and his consent to the processing of the personal data used in this context is obtained. In this context, a reference is also made to this data protection declaration.',
            9: 'The legal basis for the processing of personal data using technically necessary cookies is Art. 6 para. 1 lit. f GDPR.',
            10: 'The legal basis for the processing of personal data using cookies for analysis purposes is Art. 6 para. 1 lit. a GDPR, without consent Art. 6 para. 1 lit. f GDPR if the user has given his consent.',
            11: 'Insofar as cookies simplify the ordering process by saving settings during the ordering process (e.g. remembering the contents of a virtual shopping basket for a later visit to the website), they are processed in accordance with Art. 6 Para. 1 lit. b GDPR either to implement the contract or in accordance with Art. 6 Para. 1 lit. f GDPR to safeguard our legitimate interests in the best possible functionality of the website and a customer-friendly and effective design of the page visit.',
            12: 'The purpose of using technically necessary cookies is to simplify the use of websites for users.',
            13: 'The analysis cookies are used for the purpose of improving the quality of our website and its content. The analysis cookies tell us how the website is used and enable us to constantly optimise our services.',
            14: 'In these purposes also our legitimate interest lies in the processing of personal data in accordance with Art. 6 para. 1 lit. f GDPR.',
            15: 'Cookies are stored on the user\'s computer and transmitted to our site by the user. Therefore, you as a user have full control over the use of cookies. You can deactivate or restrict the transmission of cookies by changing the settings in your Internet browser. Cookies that have already been saved can be deleted at any time. This can also be done automatically. If cookies are deactivated for our website, it is possible that all functions of the website can no longer be used to their full extent.',
            16: 'The transmission of Flash cookies cannot be prevented via the browser settings, but by changing the settings of the Flash Player.',
          },
          ul: {
            1: 'XSRF-TOKEN: This cookie was written to increase the security of the website and prevent attacks on Cross-Site Request Forgery.',
            2: 'session: Saves a session ID in order to be able to assign several independent requests to a user session. If this is also set for visitors who are not logged in, a link to personal data can be created for a logged-in visitor. Applies only as long as the browser session is active (close browser = cookie removed).',
            3: 'i18n: Stores the visitor\'s language preference even after the actual session has ended.',
            4: 'notifications: Saves which notifications the visitor has clicked away.',
            5: 'cookies: Stores whether the visitor has clicked away the "We use cookies" overlay.',
            6: 'version: Preparations for A/B testing together, content is "production".',
            7: 'Entered search terms',
            8: 'Frequency of page views',
            9: 'Use of website functions',
          },
        },
        contact: {
          headline: 'Contact us',
          h: {
            1: 'Description and scope of data processing',
            2: 'Legal basis for data processing',
            3: 'Purpose of data processing',
            4: 'Duration of storage',
            5: 'Possibility of opposition and removal',
          },
          p: {
            1: 'Our contact details are stored on our website. You can send us a message via the e-mail address provided. In this case, the personal data of the user transmitted with the e-mail will be stored. In this context, the data will not be passed on to third parties. The data will be used exclusively for the processing of the conversation.',
            2: 'Art. 6 para. 1 lit. f GDPR is the legal basis for the processing of data transmitted in the course of sending an e-mail. If the purpose of the e-mail contact is to conclude a contract, the additional legal basis for the processing is Art. 6 para. 1 lit. b GDPR.',
            3: 'If you contact us by e-mail, your request will be processed with the necessary justified interest in the processing of the data.',
            4: 'The data will be deleted as soon as they are no longer necessary for the purpose for which they were collected. The conversation ends when it can be inferred from the circumstances that the facts in question have been conclusively clarified.',
            5: 'The user has the possibility to revoke his consent to the processing of his personal data at any time. If the user contacts us by e-mail, he can object to the storage of his personal data at any time. In such a case, the conversation cannot be continued. An e-mail to us is sufficient for the objection or revocation of consent. All personal data stored in the course of contacting us will be deleted in this case.',
          },
        },
        newsletter: {
          headline: 'Newsletter',
          h: {
            1: 'Description and scope of data processing',
            2: 'Legal basis for data processing',
            3: 'Purpose of data processing',
            4: 'Duration of storage',
            5: 'Possibility of opposition and removal',
            6: 'Shipping service provider Sendinblue',
          },
          p: {
            1: 'You can subscribe to a free newsletter on our website. When you register for the newsletter, the data from the input mask will be transmitted to us (in particular your e-mail address).',
            2: 'In addition, the following data is collected when registering for the newsletter:',
            3: 'Your consent will be obtained for the processing of your data during the registration process and reference will be made to this data protection declaration.',
            4: 'No data will be passed on to third parties in connection with data processing for the dispatch of newsletters. The data will be used exclusively for the dispatch of the newsletter.',
            5: 'The legal basis for the processing of data by the user after registration for the newsletter is Art. 6 para. 1 lit. a GDPR if the user has given his consent.',
            6: 'The collection of the user\'s e-mail address serves to deliver the newsletter.',
            7: 'The collection of other personal data as part of the registration process serves to prevent misuse of the services or the e-mail address used.',
            8: 'The data will be deleted as soon as it is no longer required for the purpose for which it was collected. The user\'s e-mail address will therefore be stored as long as the newsletter subscription is active. The other personal data collected during the registration process will generally be deleted after a period of seven days.',
            9: 'The subscription of the newsletter can be cancelled by the affected user at any time. For this purpose there is a corresponding link in every newsletter.',
            10: 'This also enables the revocation of the consent to the storage of personal data collected during the registration process.',
            11: 'Dispatch service provider: The newsletter is sent by means of "Sendinblue" (hereinafter referred to as "dispatch service provider"). You can view the privacy policy of the shipping service provider here: {sendInBlueEN}.',
            12: 'The e-mail addresses of our newsletter recipients, as well as their further data described in the context of these notes, are stored on the servers of the dispatch service provider. The shipping service provider uses this information to send and evaluate the newsletter on our behalf. Furthermore, according to its own information, the shipping service provider may use this data to optimise or improve its own services, e.g. for the technical optimisation of the dispatch and the presentation of the newsletter or for economic purposes in order to determine from which countries the recipients come. However, the shipping service provider does not use the data of our newsletter recipients to write to them itself or pass them on to third parties.',
            13: 'Registration data: To subscribe to the newsletter, it is sufficient to enter your e-mail address.',
            14: 'Statistical survey and analysis - The newsletters contain a so-called "web beacon", i.e. a file the size of a pixel, which is called up by the server of the dispatch service provider when the newsletter is opened. Within the scope of this retrieval, technical information, such as information about the browser and your system, as well as your IP address and time of retrieval are first collected. This information is used for the technical improvement of the services on the basis of the technical data or the target groups and their reading behaviour on the basis of their retrieval locations (which can be determined with the help of the IP address) or the access times. Statistical surveys also include determining whether newsletters are opened, when they are opened and which links are clicked. For technical reasons, this information can be assigned to the individual newsletter recipients. However, it is neither our nor the shipping service provider\'s aim to observe individual users. The evaluations serve us much more to recognize the reading habits of our users and to adapt our contents to them or to send different contents according to the interests of our users.',
            15: 'Cancellation/revocation - You can cancel the receipt of our newsletter at any time, i.e. revoke your consent. At the same time, your consents to its dispatch by the dispatch service provider and the statistical analyses expire. A separate revocation of the shipment by the shipping service provider or the statistical analysis is unfortunately not possible. You will find a link to cancel the newsletter at the end of each newsletter.',
          },
          ul: {
            1: 'IP address of the calling computer',
            2: 'Date and time of registration',
          },
        },
        signUp: {
          headline: 'Registration and Login',
          h: {
            1: 'Description and scope of data processing',
            2: 'Legal basis for data processing',
            3: 'Purpose of data processing',
            4: 'Duration of storage',
            5: 'Possibility of opposition and removal',
            6: 'Social Login',
            7: 'Legal basis for data processing Social Login',
            8: 'Purpose of data processing Social Login',
            9: 'Duration of storage Social Login',
            10: 'Objection and removal option Social Login',
          },
          p: {
            1: 'On our website, we offer users the opportunity to register by providing personal data. The data is entered into an input mask and transmitted to us and stored. The data will not be passed on to third parties. The following data is collected as part of the registration process: Your e-mail address, name, address and user name.',
            2: 'In addition, the following data is collected during registration:',
            3: 'Your consent will be obtained for the processing of your data during registration and reference will be made to this data protection declaration.',
            4: 'The legal basis for the processing of the data is Art. 6 para. 1 lit. a GDPR if the user has given his consent.',
            5: 'A registration of the user is necessary for the provision of certain contents and services on our website. In particular, the use of our chargeable offers is only possible after registration.',
            6: 'The data will be deleted as soon as they are no longer required for the purpose for which they were collected. This applies to the data collected during the registration process if the registration on our website is cancelled or modified.',
            7: 'As a user you have the possibility to cancel the registration at any time. You can have the data stored about you changed at any time. Please send us an e-mail.',
            8: 'For the registration and login to the customer account you also have the possibility to authenticate yourself with your existing profile on one of the following social networks, Facebook or Google+ and finally register or log in.',
            9: 'For this purpose, you will find on the registration page or login page the corresponding symbols of the respective providers of the social networks supported by our website. Before connecting to the provider, you must expressly consent to the process and data transfer described below.',
            10: 'By clicking on the respective symbol, a new window (so-called app) will open, where you have to log in with your login data for the social network. After you have successfully logged in, the social network will inform you which data (name and e-mail address) is transmitted to us for authentication as part of the registration or login process. If you have agreed to this data transfer, the fields required by us for registration will be filled with the transferred data. The data required by us for registration or login are (i) your name and (ii) your e-mail address.',
            11: 'Only after your express consent to the use of the transmitted and required data will your data be stored by us and used for the above-mentioned purposes. A link beyond the authentication process between the customer account created with us and your account with the corresponding social network does not take place.',
            12: 'In order to carry out the authentication process for registration and login, your IP address will be transmitted to the respective social network provider. We have no influence on the purpose and scope of the data collection and the further processing of the data by the respective social network provider. For further information, please read the privacy policy of the respective provider.',
            13: '{strong} Facebook Inc., 1601 S California Ave, Palo Alto, California 94304, USA; {fbPolicy} further information on data collection: {fbHelp}, {fbInfo} as well as {fbInfoEveryone}. Facebook has submitted to the EU-US Privacy Shield, {fbFramework}.',
            14: '{strong} Google Inc., 1600 Amphitheater Parkway, Mountainview, California 94043, USA; {googlePrivacy}. Google has submitted to the EU-US Privacy Shield, {googleFramework}.',
            15: 'The legal basis for the processing of data transmitted by social networks is Art. 6 para. 1 lit. a GDPR. The respective user must consent to the transfer of this data.',
            16: 'The processing of personal data serves the sole purpose of optimizing the registration and is not necessarily to be used.',
            17: 'The personal data collected here will be deleted immediately after authentication and completion of the registration process.',
            18: 'You can object to the use of login data from social networks at any time and stop logging in via this service. In this case, you can only use the classic registration via e-mail and password to use the app.',
          },
          ul: {
            1: 'IP address of the requesting computer',
            2: 'Date and time of registration',
          },
        },
      },
      social: {
        headline: 'Social Media:',
        p: {
          1: 'Our website uses social media buttons (Facebook, Google, Twitter) to enable you to interact with third parties. These social media buttons are not integrated as plug-ins via a so-called iFrame, but are stored as links. By pressing the social media buttons you will be forwarded directly to the page of the corresponding provider. The respective provider is then responsible in the sense of Art. 4 No. 17 GDPR for compliance with the data protection regulations and for the correctness, up-to-dateness and completeness of the information provided there for data processing.',
          2: 'We have no influence on the collected data and data processing operations, nor are we aware of the full scope of data collection, the purposes of processing, the storage periods.',
          3: 'Further information on the purpose and scope of data collection and processing by the social media provider can be found in the privacy statements of these providers. There you will also find further information on your rights in this regard and setting options to protect your privacy.',
        },
      },
      webanalyse: {
        headline: 'Web analysis / user-based online advertising:',
        google: {
          headline: 'Web analysis by google Analytics',
          p: {
            1: 'We use Google Analytics, a web analytics service provided by Google Inc. ("Google"), for the purpose of tailoring our website to meet your needs and continually optimising it. "("Google"). Web analysis is the collection, collection and evaluation of data on the behaviour of visitors to websites. Among other things, a web analysis service collects data on which website a visitor came to a website from (so-called referrer), which subpages of the website were accessed or how often and for how long a subpage of the website was accessed or how often and for how long a subpage was viewed. A web analysis is mainly used to optimise a website and to analyse the costs and benefits of Internet advertising.',
            2: 'The operating company of the Google Analytics component is Google Inc, 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, USA.',
            3: 'The use is based on Art. 6 Para. 1 S. 1 lit. f GDPR. Google Analytics uses „cookies“, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website such as:',
            4: 'are transferred to servers and stored there. The information is used to evaluate the use of the website, to compile reports on the website activities and to provide further services related to the use of the website and the Internet for purposes of market research and needs-based design of this website. This information may also be transferred to third parties if this is required by law or if third parties process this data on behalf of third parties.',
            5: 'Under no circumstances will the IP address be associated with other data relating to the user. We use the addition „_gat._anonymizeIp“ for the web analysis via Google Analytics. This addition shortens and anonymizes the IP address of Google\'s Internet connection if the website is accessed from a member state of the European Union or another state party to the Agreement on the European Economic Area.',
            6: 'The user may refuse the use of cookies by selecting the appropriate settings on his browser, however please note that if you do this you may not be able to use the full functionality of this website.',
            7: 'The user can object to the creation of user profiles at any time. To do this, you must download and install a browser add-on under the link {googleTools}. This browser add-on informs Google Analytics via JavaScript that no data and information on visits to Internet pages may be transmitted to Google Analytics. The installation of the browser add-on is regarded by Google as an objection. If the data subject\'s information technology system is deleted, formatted or re-installed at a later date, you must re-install the browser add-on to deactivate Google Analytics. If the browser add-on is uninstalled or deactivated by you or another person within your control, there is a possibility of reinstalling or reactivating the browser add-on.',
            8: 'We continue to use Google Analytics to evaluate data from double-click cookies and AdWords for statistical purposes. If you do not wish this, you can deactivate it via the ad preferences manager ({onWeb}).',
            9: 'More information and Google\'s current privacy policy can be found at {googlePrivacyEN} and at {googleTermsEN} Google Analytics is explained in more detail at this link {googleAnalyticsEN}.',
            10: 'The legal basis for the processing of users\' personal data is Art. 6 para. 1 lit. f GDPR.',
            11: 'The processing of users\' personal data enables us to analyse the surfing behaviour of our users. By evaluating the data collected, we are able to compile information about the use of the individual components of our website. This helps us to constantly improve our website and its user-friendliness. In these purposes, our legitimate interest lies in the processing of data in accordance with Art. 6 Para. 1 lit. f GDPR. By anonymizing the IP address, the interest of users in the protection of their personal data is sufficiently taken into account.',
          },
          ul: {
            1: 'Browser type / version,',
            2: 'operating system used,',
            3: 'Referrer URL (the previously visited page),',
            4: 'Host name of the accessing computer (IP address),',
            5: 'Time of the server request',
          },
        },
        facebook: {
          headline: 'Facebook-Pixel, Custom Audiences and Facebook-Conversion',
          p: {
            1: 'Due to our justified interest in the analysis, optimisation and economic operation of our website and for these purposes, the so-called "Facebook pixel" of the social network Facebook, which is operated by Facebook Inc., 1 Hacker Way, Menlo Park, CA 94025, USA or, if you are resident in the EU, Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland ("Facebook"), is used on our website on account of our justified interest in the analysis, optimisation and economic operation of our offer. These purposes also include our legitimate interest in data processing pursuant to Art. 6 Para. 1 lit. f GDPR.',
            2: 'Facebook is certified under the Privacy Shield Agreement and thus offers a guarantee of compliance with European data protection law ({privacyShield}).',
            3: 'With the help of Facebook pixels, Facebook is able on the one hand to determine the visitors of our online offer as the target group for the presentation of ads (so-called "Facebook ads"). Accordingly, we use Facebook pixels to display Facebook ads placed by us only to those Facebook users who have shown an interest in our online offering or who have certain characteristics (e.g. interests in certain topics or products that are determined on the basis of the websites visited) that we transmit to Facebook (so-called "custom audiences"). Using Facebook pixels, we also want to ensure that our Facebook ads correspond to the potential interest of users and do not act as a nuisance. Using Facebook pixels, we can also track the effectiveness of Facebook ads for statistical and market research purposes by seeing if users were referred to our website after clicking on a Facebook ad (known as "conversion").',
            4: 'Facebook processes the data in accordance with the Facebook Data Usage Policy. Accordingly, general information on the presentation of Facebook ads in Facebook\'s data usage policy: {fbPolicy}. Special information and details about the Facebook pixel and how it works can be found in the help section of Facebook: {fbHelp}.',
            5: 'You may opt out of Facebook pixel collection and use of your information to display Facebook ads. To set what types of ads you see within Facebook, you can go to the page set up by Facebook and follow the instructions there about the settings for usage-based ads: {fbSettings}. The settings are platform-independent, i.e. they are applied to all devices, such as desktop computers or mobile devices.',
            6: 'You may also opt-out of the use of cookies to measure reach and for advertising purposes via the Network Advertising Initiative opt-out page ({networkAdvertising}) and the US website ({aboutAds}) or the European website ({ukChoices}).',
            7: 'The legal basis for the use of this service is Art. 6 para. 1 sentence. 1 letter f GDPR.',
            8: 'According to its own information, Facebook stores the date and time of the visit, the specific Internet address where the social plugin is located, and other technical data such as the IP address, browser type and operating system for a period of 90 days in order to further optimize Facebook\'s services. After 90 days, the data is anonymized so that it cannot be further associated with a specific person.',
          },
        },
        twitter: {
          headline: 'Conversion measurement with the „Twitter-Pixel“',
          p: {
            1: 'On our pages, functions of the Twitter service are integrated. These functions are offered by Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA. By using Twitter and the "Re-Tweet" function, the websites you visit are linked to your Twitter account and made known to other users. Data is also transferred to Twitter in the process. We would like to point out that, as the provider of the pages, we do not have any knowledge of the content of the transmitted data or its use by Twitter.',
            2: 'With the help of the „Twitter-Pixel“ set on our pages, we can track the actions of users in particular after they have seen or clicked on a Twitter ad. This process is used to evaluate the effectiveness of Twitter advertisements for statistical and market research purposes and may help optimize future advertising efforts. The data collected is anonymous to us so that we cannot draw any conclusions about the identity of users. However, the data is stored and processed by Twitter so that a connection to the respective user profile is possible and Twitter can use the data for its own advertising purposes in accordance with the Twitter Privacy Policy. You may enable Twitter and its partners to place advertisements on and outside Twitter. A cookie may also be stored on your computer for these purposes. You can find more information about this in Twitter\'s privacy policy at {twitterPrivacy}.',
            3: 'The legal basis for the use of this service is Art. 6 para. 1 sentence. 1 letter f GDPR. You may object to Twitter pixel collection and use of your data at the following address: {twitterDoNotTrackEN}.',
            4: 'Twitter is certified under the Privacy Shield Agreement and thus offers a guarantee of compliance with European data protection law ({privacyShield}).',
          },
        },
      },
      rights: {
        headline: 'Rights of the data subject:',
        description: 'If personal data is processed by you, you are the data subject within the meaning of the GDPR and you are entitled to the following rights vis-à-vis the person responsible:',
        information: {
          headline: 'Right to information',
          p: {
            1: 'You can request confirmation from the person responsible as to whether personal data relating to you will be processed by us.',
            2: 'In the event of such processing, you may request the following information from the data controller:',
            3: 'You have the right to request information as to whether the personal data concerning you will be transferred to a third country or to an international organisation. In this context, you may request to be informed of the appropriate guarantees pursuant to Art. 46 GDPR in connection with the transfer.',
          },
          ul: {
            1: '(1) the purposes for which the personal data are processed.',
            2: '(2) the categories of personal data processed.',
            3: '(3) the recipients or categories of recipients to whom the personal data relating to you has been or will be disclosed.',
            4: '(4) the planned duration of storage of the personal data relating to you or, if this is not possible, criteria for determining the duration of storage.',
            5: '(5) the existence of a right to rectify or delete personal data concerning you, a right to limit the processing by the controller or a right to object to such processing.',
            6: '(6) the existence of a right of appeal to a supervisory authority.',
            7: '(7) all available information on the source of the data, if the personal data are not collected from the data subject.',
            8: '(8) the existence of automated decision-making, including profiling, in accordance with Article 22(1) and (4) GDPR and - at least in these cases - meaningful information on the logic involved and the scope and intended effects of such processing for the data subject.',
          },
        },
        rectification: {
          headline: 'Right to rectification',
          p: {
            1: 'You have the right to have your personal data corrected and/or completed by the data controller if the personal data processed concerning you is inaccurate or incomplete. The data controller must carry out the rectification immediately.',
          },
        },
        processing: {
          headline: 'Right to limitation of processing',
          p: {
            1: 'Under the following conditions, you may request that the processing of your personal data be restricted:',
            2: 'Where the processing of personal data concerning you has been restricted, such data may not be processed, with the exception of their storage, without your consent or for the purpose of asserting, exercising or defending rights or protecting the rights of another natural or legal person or for reasons of an important public interest of the Union or of a Member State.',
            3: 'If the processing restriction has been restricted in accordance with the above conditions, you will be informed by the controller before the restriction is lifted.',
          },
          ul: {
            1: '(1) if you dispute the accuracy of the personal data concerning you for a period of time which enables the person responsible to verify the accuracy of the personal data.',
            2: '(2) the processing is unlawful and you refuse to delete the personal data and instead request the restriction of the use of the personal data.',
            3: '(3) the controller no longer needs the personal data for the purposes of processing, but you need them to assert, exercise or defend legal claims, or',
            4: '(4) if you have objected to the processing pursuant to Art. 21 para. 1 GDPR and it has not yet been established whether the legitimate reasons of the data controller outweigh your reasons.',
          },
        },
        deletion: {
          headline: 'Right to deletion',
          h: {
            1: 'Obligation to delete',
            2: 'Information to third parties',
            3: 'Exemptions',
          },
          p: {
            1: 'You may request the data controller to delete the personal data concerning you immediately and the data controller is obliged to delete this data immediately if one of the following reasons applies:',
            2: 'If the person responsible has made the personal data concerning you public and is obliged to delete them in accordance with Art. 17 (1) GDPR, he shall take appropriate measures, including technical measures, taking into account the available technology and the implementation costs, to inform the persons responsible for data processing who process the personal data that you, as the person concerned, have requested them to delete all links to this personal data or copies or replications of this personal data.',
            3: 'The right to deletion does not exist insofar as processing is necessary.',
          },
          ul: {
            1: '(1) The personal data relating to you are no longer necessary for the purposes for which they were collected or otherwise processed.',
            2: '(2) You revoke your consent on which the processing pursuant to Art. 6 para. 1 lit. a or Art. 9 para. 2 lit. a GDPR was based and there is no other legal basis for the processing.',
            3: '(3) You object to the processing pursuant to Art. 21 para. 1 GDPR and there are no overriding legitimate reasons for the processing or you object to the processing pursuant to Art. 21 para. 2 GDPR.',
            4: '(4) The personal data concerning you have been processed unlawfully.',
            5: '(5) The deletion of personal data concerning you is necessary to fulfil a legal obligation under Union law or the law of the Member States to which the data controller is subject.',
            6: '(6) The personal data relating to you have been collected in relation to information society services offered pursuant to Art. 8 para. 1 GDPR.',
            7: '(1) the exercise of freedom of expression and information.',
            8: '(2) to fulfil a legal obligation which the processing requires under the law of the Union or of the Member States to which the controller is subject or to carry out a task carried out in the public interest or in the exercise of official authority vested in the controller.',
            9: '(3) for reasons of public interest in the field of public health pursuant to Art. 9 para. 2 lit. h and i and Art. 9 para. 3 GDPR.',
            10: '(4) for archival purposes in the public interest, scientific or historical research purposes or for statistical purposes pursuant to Art. 89 para. 1 GDPR, insofar as the law referred to in Section a) presumably makes the attainment of the objectives of such processing impossible or seriously impairs them, or',
            11: '(5) to assert, exercise or defend legal claims.',
          },
        },
        briefing: {
          headline: 'Right to be informed',
          p: {
            1: 'If you have exercised your right to rectify, cancel or limit the processing of your personal data against the controller, the latter is obliged to notify all recipients to whom the personal data concerning you have been disclosed of such rectification, cancellation or limitation, unless this proves impossible or involves a disproportionate effort.',
            2: 'They shall have the right vis-à-vis the person responsible to be informed of such recipients.',
          },
        },
        transferability: {
          headline: 'Right to data transferability',
          p: {
            1: 'You have the right to receive the personal data concerning you that you have provided to the data controller in a structured, common and machine-readable format. In addition, you have the right to communicate these data to another data controller without being hindered by the controller to whom the personal data was provided, provided that',
            2: 'In exercising this right, you also have the right to obtain that the personal data relating to you be transmitted directly by one responsible person to another responsible person, insofar as this is technically feasible. Freedoms and rights of other persons must not be affected by this.',
            3: 'The right to data transfer does not apply to the processing of personal data necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller.',
          },
          ul: {
            1: '(1) the processing is based on a consent pursuant to Art. 6 para. 1 lit. a GDPR or Art. 9 para. 2 lit. a GDPR or on a contract pursuant to Art. 6 para. 1 lit. b GDPR and',
            2: '(2) the processing is carried out by automated means.',
          },
        },
        objection: {
          headline: 'Right of objection',
          p: {
            1: 'You have the right, for reasons arising from your particular situation, to object at any time to the processing of your personal data on the basis of Art. 6 para. 1 lit. e or f GDPR; this also applies to profiling based on these provisions.',
            2: 'The controller will no longer process the personal data relating to you unless he can prove compelling reasons for processing worthy of protection which outweigh your interests, rights and freedoms, or the processing serves to assert, exercise or defend legal claims.',
            3: 'If the personal data concerning you are processed for the purpose of direct advertising, you have the right to object at any time to the processing of the personal data concerning you for the purpose of such advertising; this also applies to profiling to the extent that it is connected with such direct advertising.',
            4: 'If you object to the processing for direct marketing purposes, the personal data concerning you will no longer be processed for these purposes.',
            5: 'You have the possibility to exercise your right of objection in relation to the use of Information Society services - notwithstanding Directive 2002/58/EC - by means of automated procedures using technical specifications.',
          },
        },
        protectionlaw: {
          headline: 'Right to revoke the declaration of consent under data protection law',
          p: {
            1: 'You have the right to revoke your declaration of consent under data protection law at any time. The revocation of your consent does not affect the legality of the processing carried out on the basis of your consent until you revoke it.',
          },
        },
        profiling: {
          headline: 'Automated decision in individual cases including profiling',
          p: {
            1: 'You have the right not to be subject to any decision based solely on automated processing, including profiling, that has any legal effect on you or similarly significantly affects you. This does not apply if the decision',
            2: 'However, these decisions may not be based on special categories of personal data under Art. 9 para. 1 GDPR, unless Art. 9 para. 2 lit. a or g GDPR applies and appropriate measures have been taken to protect the rights and freedoms as well as your legitimate interests.',
            3: 'In the cases referred to in (1) and (3), the controller shall take reasonable steps to safeguard the rights and freedoms and your legitimate interests, including at least the right of the controller to obtain the intervention of a person, to present his or her point of view and to contest the decision.',
          },
          ul: {
            1: '(1) is necessary for the conclusion or performance of a contract between you and the person responsible,',
            2: '(2) is authorised by legislation of the Union or of the Member States to which the person responsible is subject and contains appropriate measures to safeguard your rights and freedoms and your legitimate interests; or',
            3: '(3) with your express consent.',
          },
        },
        authority: {
          headline: 'Right of appeal to a supervisory authority',
          p: {
            1: 'Without prejudice to any other administrative or judicial remedy, you shall have the right to complain to a supervisory authority, in particular in the Member State of your residence, place of work or place of presumed infringement, if you consider that the processing of your personal data is in breach of the GDPR.',
            2: 'The supervisory authority to which the complaint was submitted shall inform the complainant of the status and outcome of the complaint, including the possibility of a judicial remedy under Article 78 GDPR.',
          },
        },
      },
    },
  },
}
